global:
  domain: ifix-dwss.psegs.in
  #containerRegistry: dwssio
  tracing-enabled: false
  namespace: ifix
  nodepool:
    selector: ifix-prod-ng
    toleration: ifix-prod-ng

cluster-configs:
  namespaces:
    create: false
    values:
      [ 
        ifix, 
        cert-manager,
        olap
      ]

  rbac:
    - role: user
      namespaces: [ifix]
    - role: admin
      namespaces: [ifix]

  root-ingress:
    cert-issuer: letsencrypt-prod
    serviceName: digit-ui
    appRoot: digit-ui
  configmaps:
    egov-config:
      data:
        mongo-db-host: "ifix-prod-db.cluster-cvisvjyknxm1.ap-south-1.docdb.amazonaws.com"
        mongo-db-name: "ifixprodadmin"
        mongo-db-url: "mongodb://ifix-prod-db.cluster-cvisvjyknxm1.ap-south-1.docdb.amazonaws.com:27017/?retryWrites=false"
        db-host: "magramsewa-prod-db.cvisvjyknxm1.ap-south-1.rds.amazonaws.com"
        db-name: "ifix_prod_db"
        keycloak-db-name: "keycloak_prod_db"
        db-url: "jdbc:postgresql://magramsewa-prod-db.cvisvjyknxm1.ap-south-1.rds.amazonaws.com:5432/ifix_prod_db"
        domain: "ifix-dwss.psegs.in"
        egov-services-fqdn-name: "https://ifix-dwss.psegs.in/"
        egov-state-level-tenant-id: "pb"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/qa"
        kafka-brokers: "kafka-v2.ifix:9092"
        kafka-infra-brokers: "kafka-v2.ifix:9092"
        logging-level-jdbc: "debug"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-threads: "10"
        server-tomcat-max-connections: "500"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "5"
        spring-jpa-show-sql: "true"
        tracer-errors-provideexceptionindetails: "true"
        timezone: "Asia/Kolkata"
        druid-host: "druid-broker.olap"
        es-indexer-host: "http://elasticsearch-data-v1.mgramseva:9200/"

    egov-service-host:
      data:
        ifix-master-data-service: "http://ifix-master-data-service.ifix:8080/"
        fiscal-event-service: "http://fiscal-event-service.ifix:8080/"
        ifix-zuul: "http://ifix-zuul.ifix:8080/"
        ifix-department-entity-service: "http://ifix-department-entity-service.ifix:8080/"
        keycloak: "http://keycloak.ifix:8080/"
        redis-host: "redis.ifix"
        egov-indexer: "http://egov-indexer.ifix:8080/"
        dashboard-analytics: "http://dashboard-analytics.ifix:8080/"
        egov-mdms-service: "http://egov-mdms-service.mgramseva:8080/"
        ifix-department-entity-service: "http://ifix-department-entity-service.mgramseva:8080/"

ifix-es-pipeline:
  fiscal-event-kafka-push-topic: "fiscal-event-request-validated"
  fiscal-event-es-push-topic: "index-fiscal-events"
  ifix-department-entity-search-endpoint: "ifix-department-entity/departmentEntity/hierarchyLevel/v1/_search"
  ifix-master-data-service-search-endpoint: "ifix-master-data/chartOfAccount/v1/_search"
  fiscal-events-migration-topic: "ifix-fiscal-events-migrate"
  fiscal-event-migration-origin-push-topic: "ifix-fiscal-events-migration-origin"

egov-mdms-service:
  mdms-path: "/work-dir/mdms-mgramseva/data"
  mdms-folder: "mdms-mgramseva"
  java-args: -Dspring.profiles.active=monitoring
  masters-config-url: "file:///work-dir/mdms-mgramseva/master-config.json"
  initContainers:
    gitSync:
      repo: "git@github.com:misdwss/mdms-mgramseva"
      branch: "master"

digit-ui:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://s3.ap-south-1.amazonaws.com/ifix-dev-assets/globalProdConfigs.js type=text/javascript></script>
      ';"
dashboard-analytics:
  config-schema-paths: "file:///work-dir/config-mgramseva/egov-dss-dashboards/dashboard-analytics/*.json"
  initContainers:
    gitSync:
      enabled: true
      repo: "git@github.com:misdwss/config-mgramseva"
      branch: "master"

egov-persister:
  persist-yml-path: "file:///work-dir/config-mgramseva/egov-persister/ifix-migration-progress.yml"
  initContainers:
    gitSync:
      enabled: true
      repo: "git@github.com:misdwss/config-mgramseva"
      branch: "master"

ifix-migration-toolkit:
  fiscal-event-kafka-push-topic: "fiscal-event-request-validated"
  fiscal-event-es-push-topic: "index-fiscal-events"
  ifix-migration-batch-size: "200"
  ifix-department-entity-search-endpoint: "ifix-department-entity/departmentEntity/hierarchyLevel/v1/_search"

        
ifix-master-data-service:
  server-context-path: "/ifix-master-data"

fiscal-event-service:
  fiscal-kafka-push-topic: "fiscal-event-request-validated"
  fiscal-event-push-request-max-size: "1000"

fiscal-event-post-processor:
  fiscal-event-kafka-push-topic: "fiscal-event-request-validated"
  fiscal-event-kafka-dereferenced-topic: "fiscal-event-request-dereferenced"
  fiscal-event-kafka-flattened-topic: "fiscal-event-line-item-flattened"
  fiscal-event-processor-kafka-mongodb-topic: "fiscal-event-mongodb-sink"
  fiscal-event-processor-kafka-druid-topic: "fiscal-event-druid-sink"
  
ifix-zuul:
  replicas: 1
  custom-filter-property: "false"
  tracing-enabled: "true"
  heap: "-Xmx704m -Xms512m"
  server-tomcat-max-threads: "350"
  server-tomcat-max-connections: "1500"
  egov-open-endpoints-whitelist: "/ifix-master-data/government/v1/_search,/ifix-master-data/chartOfAccount/v1/_search,/ifix-master-data/department/v1/_search,/ifix-master-data/expenditure/v1/_search,/ifix-master-data/project/v1/_search,/ifix-department-entity/departmentEntity/v1/_search,/ifix-department-entity/departmentEntity/hierarchyLevel/v1/_search"
  egov-mixed-mode-endpoints-whitelist: ""
  
fiscal-event-aggregator:
  aggregator-topic-name: "aggregated-fiscal-event"
  aggregator-datasource-name: "fiscal-event"

mongodb-kafka-source-connector:
  mongodb-collection-name: "fiscal_event"
  kafka-topic: "fiscal-event-request-validated"

druid:
  domain: druid-dwss.psegs.in
  storage: aws
  aws:
    druid_storage_type: s3
    druid_storage_baseKey: druid/segments
    druid_storage_bucket: ifix-prod-assets

middleManager:
    replicaCount: 1
    config:
      DRUID_XMX: 3500m
      DRUID_XMS: 3500m
      druid_indexer_runner_javaOptsArray: '["-server", "-Xms1g", "-Xmx1g", "-XX:MaxDirectMemorySize=1600m", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-XX:+ExitOnOutOfMemoryError", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]'
      druid_indexer_fork_property_druid_processing_buffer_sizeBytes: '400000000'
    resources: 
      limits:
        cpu: 900m
        memory: 5000Mi
      requests:
        cpu:  900m
        memory: 4500Mi  

historical:
    replicaCount: 1
    config:
      DRUID_XMX: 3000m
      DRUID_XMS: 3000m
      DRUID_MAXDIRECTMEMORYSIZE: 1300m
      druid_processing_buffer_sizeBytes: '300000000'
      druid_processing_numMergeBuffers: 2
      druid_processing_numThreads: 1
      druid_javascript_enabled: true
    resources: 
      limits:
        cpu: 900m
        memory: 3500Mi
      requests:
        cpu:  700m
        memory: 3500Mi   
  
coordinator:
    replicaCount: 1
    config:
      DRUID_XMX: 3300m
      DRUID_XMS: 3300m
    resources: 
      limits:
        cpu: 900m
        memory: 3500Mi
      requests:
        cpu:  600m
        memory: 3500Mi
        
overlord:
    replicaCount: 1
    resources: 
      limits:
        cpu: 900m
        memory: 5000Mi
      requests:
        cpu:  900m
        memory: 4500Mi

router:
  ingress:
    additionalAnnotations: |
      nginx.ingress.kubernetes.io/auth-signin:  https://$host/oauth2/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url:     https://$host/oauth2/auth     

metabase:
  domain: metabase-dwss.psegs.in
  siteUrl: metabase-dwss.psegs.in

# Oauth2=proxy >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
oauth2-proxy:
  namespaces: ifix
  config:
    configFile: |-
      email_domains = [ "*" ]
      github_org = "misdwss"
      github_team = "mgramsewa-prod,devops-team"
      upstreams = [ "file:///dev/null" ]

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

kafka-v2:
  image:
    tag: 5.4.1
  persistence:
    enabled: true
    aws:
      - volumeId: "vol-0e50e13d07da3dfb5"
        zone: ap-south-1a
      - volumeId: "vol-0f346c61d0e22e6df"
        zone: ap-south-1a
      - volumeId: "vol-00ffdb1bcf49e6d23"
        zone: ap-south-1a
  zookeeperHosts: "zookeeper-v2.ifix:2181/kafka-v2"

  heapOptions: "-Xms704M -Xmx704M"
  memory_limits: 1408Mi
  lingerMs: "250"
  numberPartitions: "3"
  replicationFactor: "2"
  minInsyncReplicas: "1"
  offsetsReplicationFactor: "3"

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
kafka-connect:
 image:
   repository: kafka-connect-mongo
   tag: 1.5.1

# zookeeper-v2 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
zookeeper-v2:
  persistence:
    enabled: true
    aws:
      - volumeId: "vol-05932720d35668b4f"
        zone: ap-south-1a
      - volumeId: "vol-0cdbeb8692142851c"
        zone: ap-south-1a
      - volumeId: "vol-06a105e4b0bfbb761"
        zone: ap-south-1a

  ## Zookeeper JVM Heap Option
  heapOptions: "-Xms256M -Xmx256M"
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 300m
      memory: 384Mi

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

playground:
  replicas: 1
  images:
    - egovio/playground:mongo-v1

postgres:
  postgresDatabase: ifix_qa_db
  persistence:
    enabled: true
    aws:
      volumeId: "vol-0b62ac5eb48fe9987"
