{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.metabase.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "name" . }}
              servicePort: {{ .Values.ingress.servicePort }}
  tls:     
  - hosts:
    - {{ .Values.metabase.domain }}
    secretName: {{ .Values.metabase.domain }}-tls-certs 
{{- end -}}

