{{- if .Values.broker.ingress.enabled -}}
{{- $fullName := include "druid.broker.fullname" . -}}
{{- $ingressPath := .Values.broker.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    component: {{ .Values.broker.name }}
    heritage: {{ .Release.Service }}
{{- with .Values.broker.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.broker.ingress.tls }}
  tls:     
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.domain }}-tls-certs 
{{- end }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /{{ .Values.broker.ingress.path }}
            backend:
              serviceName: {{ include "druid.broker.fullname" . }}
              servicePort: http
{{- end }}
