# Common Labels
labels:
  app: "fiscal-event-service"
  group: "ifix"

namespace: ifix

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "fiscal-events"

# Container Configs
image:
  repository: "fiscal-event-service"
replicas: "1"

appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

server-context-path: "/fiscal-events"

# Additional Container Envs
env: |  
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: {{ index .Values "server-context-path" | quote }}
  - name: SERVER_PORT
    value: "8080"
