# Common Labels
labels:
  app: "fiscal-event-service"
  group: "ifix"

namespace: ifix

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "fiscal-event-service"

# Container Configs
image:
  repository: "fiscal-event-service"
replicas: "1"

appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

server-context-path: "/fiscal-event-service"

# Additional Container Envs
env: |  
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: {{ index .Values "server-context-path" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: IFIX_MASTER_GOVERNMENT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-master-data-service
  - name: IFIX_MASTER_COA_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-master-data-service
  - name: IFIX_MASTER_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-master-data-service
  - name: FISCAL_KAFKA_PUSH_TOPIC
    value: "fiscal-event-request-validated"
