# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used

        - path_regex: environments/bihar-mgramseva\-uat\-secrets\.yaml$   #mgramseva-uat
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:197939965038:key/c062b4a9-5aed-4843-b705-3cca5cd777df'

        - path_regex: environments/bihar-mgramseva\-prod\-secrets\.yaml$   #mgramseva-uat
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:197939965038:key/c062b4a9-5aed-4843-b705-3cca5cd777df'
