# Common Labels
labels:
  app: "ifix-reference-adapter"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: false
  zuul: false
  context: "ifix-adapter"

# Init Containers Configs
initContainers:

# Container Configs
image:
  repository: "ifix-reference-adapter"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/ifix-adapter/health"
  readinessProbePath: "/ifix-adapter/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: KEYCLOAK_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: keycloak
  - name: IFIX_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: fiscal-event-service
  - name: SERVER_PORT
    value: "8080"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: ifix-adaptor-mapper
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  {{- end }}

